version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

  migrate:
    build:
      context: .
      dockerfile: ./shared/database/Dockerfile.migrate
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  processor:
    build:
      context: .
      dockerfile: ./file-processor/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - WORKER_COUNT=${WORKER_COUNT:-3}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb?connection_limit=50&pool_timeout=20
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./file-processor:/app
      - ./shared/database/prisma:/app/prisma
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G # Reduced from 2G
        reservations:
          cpus: "0.25" # Reduced from 0.5
          memory: 512M # Reduced from 1G

  api:
    build:
      context: .
      dockerfile: ./database-api/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "4040:4040"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb?connection_limit=20&pool_timeout=20
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./database-api:/app
      - ./shared/database/prisma:/app/prisma
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  postgres_data:
  redis_data:
